# Generated by Django 5.2.7 on 2025-10-25 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Language Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='ISO Code (e.g., EN, FR)')),
                ('flag_icon', models.CharField(blank=True, max_length=50, verbose_name='Flag Icon')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Reward Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(max_length=100, verbose_name='Reward Icon')),
                ('points_required', models.IntegerField(default=0, verbose_name='Points Required to Unlock')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Game Title')),
                ('game_type', models.CharField(choices=[('QUIZ', 'Quiz'), ('MEMORY', 'Memory Game'), ('WORD_SEARCH', 'Word Search'), ('LISTENING', 'Listening Comprehension')], max_length=20, verbose_name='Game Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('difficulty', models.IntegerField(default=1, verbose_name='Difficulty Level (1-5)')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.language', verbose_name='Associated Language')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Challenge Title')),
                ('description', models.TextField(verbose_name='Challenge Description')),
                ('points_reward', models.IntegerField(default=10, verbose_name='Reward Points')),
                ('is_daily', models.BooleanField(default=False, verbose_name='Is Daily Challenge')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
            },
        ),
        migrations.CreateModel(
            name='UserChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Challenge Completed')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Completion Date')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.challenge', verbose_name='Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Challenge Progress',
                'verbose_name_plural': 'User Challenge Progresses',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0, verbose_name='Current Learning Streak (days)')),
                ('total_points', models.IntegerField(default=0, verbose_name='Total Points')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Avatar')),
                ('languages_learning', models.ManyToManyField(to='shop.language', verbose_name='Languages Learning')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Unlock Date')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.reward', verbose_name='Reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Reward',
                'verbose_name_plural': 'User Rewards',
            },
        ),
    ]
