# Generated by Django 5.2.7 on 2025-10-30 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Difficult'), (4, 'Expert'), (5, 'Legendary')], default=1, verbose_name='Difficulty Level (1-5)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages_learning',
            field=models.ManyToManyField(to='shop.language', verbose_name='Languages being Learned'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallengeprogress',
            unique_together={('user', 'challenge')},
        ),
        migrations.AlterUniqueTogether(
            name='userreward',
            unique_together={('user', 'reward')},
        ),
    ]
