# Generated by Django 5.2.7 on 2025-10-30 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_game_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='External Game URL'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Is External Game'),
        ),
        migrations.CreateModel(
            name='UserGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.game', verbose_name='Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
